name: Winston Personality Module
skillMetadata:
  sections:
    - name: Owner customization
      fields:
        - name: animatronic_name
          type: text
          label: Name of animatronic
          value: ""
          placeholder: demo prompt in the input box
